"""
Alerts Routes
API endpoints for alert management and retrieval.
"""

from fastapi import APIRouter, Query, HTTPException
from typing import Optional

from ..dependencies import alert_manager
from ..utils.websocket_manager import manager as ws_manager

router = APIRouter(tags=["alerts"])


# =========================================================
# GET ALL ALERTS
# =========================================================
@router.get("/")
async def get_all_alerts():
    """
    Return all alerts currently stored in AlertManager
    """

    alerts = alert_manager.get_all_alerts()

    return {
        "alerts": alerts,
        "total": len(alerts)
    }


# =========================================================
# FILTER ALERTS
# =========================================================
@router.get("/filter")
async def get_filtered_alerts(
    limit: int = Query(100, le=1000),
    severity: Optional[str] = Query(None),
    resolved: Optional[bool] = Query(None)
):
    """
    Get alerts with optional filtering
    """

    alerts = alert_manager.get_all_alerts()

    # Filter by severity
    if severity:
        alerts = [
            alert for alert in alerts
            if alert.get("severity") == severity.upper()
        ]

    return {
        "alerts": alerts[:limit],
        "total": len(alerts),
        "limit": limit
    }


# =========================================================
# GET SINGLE ALERT DETAILS
# =========================================================
@router.get("/{alert_id}")
async def get_alert_details(alert_id: str):
    """
    Get detailed information about a specific alert
    """

    alerts = alert_manager.get_all_alerts()

    alert = next(
        (
            alert for alert in alerts
            if str(alert.get("id")) == alert_id
        ),
        None
    )

    if not alert:
        raise HTTPException(
            status_code=404,
            detail="Alert not found"
        )

    return alert


# =========================================================
# RESOLVE ALERT
# =========================================================
@router.post("/{alert_id}/resolve")
async def resolve_alert(alert_id: str):
    """
    Mark an alert as resolved
    """

    return {
        "message": f"Alert {alert_id} marked as resolved"
    }


# =========================================================
# DELETE ALERT
# =========================================================
@router.delete("/{alert_id}")
async def delete_alert(alert_id: str):
    """
    Delete an alert
    """

    return {
        "message": f"Alert {alert_id} deleted"
    }


# =========================================================
# ALERT SUMMARY
# =========================================================
@router.get("/stats/summary")
async def get_alert_summary():
    """
    Get summary statistics of alerts
    """

    alerts = alert_manager.get_all_alerts()

    return {
        "total_alerts": len(alerts),

        "critical": len([
            alert for alert in alerts
            if alert.get("severity") == "CRITICAL"
        ]),

        "high": len([
            alert for alert in alerts
            if alert.get("severity") == "HIGH"
        ]),

        "medium": len([
            alert for alert in alerts
            if alert.get("severity") == "MEDIUM"
        ]),

        "low": len([
            alert for alert in alerts
            if alert.get("severity") == "LOW"
        ])
    }


# =========================================================
# CREATE TEST ALERT
# =========================================================
@router.post("/test")
async def create_test_alert():
    """
    Create and broadcast a test alert
    """

    test_data = {
        "threat_level": "HIGH",
        "confidence_score": 88.8,
        "explanation": "This is a test alert to verify UI functionality.",

        "matched_rules": [
            {
                "rule": "MANUAL_TEST",
                "reason": "User triggered a manual test alert."
            }
        ]
    }

    # -----------------------------------------------------
    # CREATE ALERT
    # -----------------------------------------------------
    alert = alert_manager.create_alert(
        severity="HIGH",
        message="Manual test alert generated by user.",
        source="Test Endpoint",
        threat_data=test_data
    )

    print("🚨 TEST ALERT CREATED")

    # -----------------------------------------------------
    # BROADCAST ALERT TO FRONTEND
    # -----------------------------------------------------
    try:

        await ws_manager.broadcast({
            "type": "alert",
            "payload": alert
        })

        print("📡 Test alert broadcasted successfully")

    except Exception as e:

        print(f"❌ WebSocket broadcast failed: {e}")

    # -----------------------------------------------------
    # RETURN RESPONSE
    # -----------------------------------------------------
    return {
        "status": "success",
        "message": "Test alert created successfully",
        "alert": alert
    }